server:
  port: 8891

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fundanalyzer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  thymeleaf:
    encoding: UTF-8

logging:
  config: classpath:log4j2-spring-dev.xml

management:
  metrics:
    tags:
      application: ${spring.application.name}-dev
