spring:
  profiles:
    # dev | prod
    active: dev
  application:
    name: fundanalyzer-patch

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: web

management:
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 400ms
    tags:
      application: ${spring.application.name}
