server:
  port: 9890

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundanalyzer?serverTimezone=Asia/Tokyo
    username: fundanalyzer
    password: fundanalyzer
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 15000
      max-lifetime: 180000
      auto-commit: true

logging:
  level:
    github.com.ioridazo.fundanalyzer: info