spring:
  profiles:
    # dev | prod
    active: dev
  application:
    name: @pom.artifactId@

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: web
