server:
  port: 9889

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fundanalyzer;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  thymeleaf:
    encoding: UTF-8

logging:
  level:
    github.com.ioridazo.fundanalyzer: debug
  config: classpath:log4j2-spring-dev.xml
